# mapping.py

def create_word_map(words_with_forms, key_length=3):
    """
    Create mapping dictionary with chords pointing to lists of word forms.
    For normal words, list has single word; for verbs, list contains forms in specified order.
    """
    word_map = {}
    for word, forms in words_with_forms.items():
        unique_letters = []
        for ch in word.lower():
            if ch not in unique_letters:
                unique_letters.append(ch)
            if len(unique_letters) == key_length:
                break
        chord_key = frozenset(unique_letters)
        word_map[chord_key] = forms
    return word_map

# Words and verbs with forms
# WORDS_WITH_FORMS
WORDS_WITH_FORMS = {
    "be": [
        "be",
        "is",
        "was",
        "been",
        "being",
        "has been",
        "had been",
        "was being",
        "will be",
        "will have been",
        "will have had been",
    ],
    "have": [
        "have",
        "has",
        "had",
        "having",
        "has had",
        "had had",
        "will have",
        "will have had",
    ],
    "do": [
        "do",
        "does",
        "did",
        "done",
        "doing",
        "has done",
        "had done",
        "will do",
        "will have done",
    ],
    "say": [
        "say",
        "says",
        "said",
        "saying",
        "has said",
        "had said",
        "will say",
        "will have said",
    ],
    "go": [
        "go",
        "goes",
        "went",
        "gone",
        "going",
        "has gone",
        "had gone",
        "will go",
        "will have gone",
    ],
    "can": [
        "can",
        "could",
    ],
    "get": [
        "get",
        "gets",
        "got",
        "gotten",
        "getting",
        "has gotten",
        "had gotten",
        "will get",
        "will have gotten",
    ],
    "would": [
        "would",
    ],
    "make": [
        "make",
        "makes",
        "made",
        "making",
        "has made",
        "had made",
        "will make",
        "will have made",
    ],
    "know": [
        "know",
        "knows",
        "knew",
        "known",
        "knowing",
        "has known",
        "had known",
        "will know",
        "will have known",
    ],
    "will": [
        "will",
    ],
    "think": [
        "think",
        "thinks",
        "thought",
        "thinking",
        "has thought",
        "had thought",
        "will think",
        "will have thought",
    ],
    "take": [
        "take",
        "takes",
        "took",
        "taken",
        "taking",
        "has taken",
        "had taken",
        "will take",
        "will have taken",
    ],
    "see": [
        "see",
        "sees",
        "saw",
        "seen",
        "seeing",
        "has seen",
        "had seen",
        "will see",
        "will have seen",
    ],
    "come": [
        "come",
        "comes",
        "came",
        "coming",
        "has come",
        "had come",
        "will come",
        "will have come",
    ],
    "could": [
        "could",
    ],
    "want": [
        "want",
        "wants",
        "wanted",
        "wanting",
        "has wanted",
        "had wanted",
        "will want",
        "will have wanted",
    ],
    "look": [
        "look",
        "looks",
        "looked",
        "looking",
        "has looked",
        "had looked",
        "will look",
        "will have looked",
    ],
    "use": [
        "use",
        "uses",
        "used",
        "using",
        "has used",
        "had used",
        "will use",
        "will have used",
    ],
    "find": [
        "find",
        "finds",
        "found",
        "finding",
        "has found",
        "had found",
        "will find",
        "will have found",
    ],
    "give": [
        "give",
        "gives",
        "gave",
        "given",
        "giving",
        "has given",
        "had given",
        "will give",
        "will have given",
    ],
    "tell": [
        "tell",
        "tells",
        "told",
        "telling",
        "has told",
        "had told",
        "will tell",
        "will have told",
    ],
    "work": [
        "work",
        "works",
        "worked",
        "working",
        "has worked",
        "had worked",
        "will work",
        "will have worked",
    ],
    "may": [
        "may",
        "might",
    ],
    "should": [
        "should",
    ],
    "call": [
        "call",
        "calls",
        "called",
        "calling",
        "has called",
        "had called",
        "will call",
        "will have called",
    ],
    "try": [
        "try",
        "tries",
        "tried",
        "trying",
        "has tried",
        "had tried",
        "will try",
        "will have tried",
    ],
    "ask": [
        "ask",
        "asks",
        "asked",
        "asking",
        "has asked",
        "had asked",
        "will ask",
        "will have asked",
    ],
    "need": [
        "need",
        "needs",
        "needed",
        "needing",
        "has needed",
        "had needed",
        "will need",
        "will have needed",
    ],
    "feel": [
        "feel",
        "feels",
        "felt",
        "feeling",
        "has felt",
        "had felt",
        "will feel",
        "will have felt",
    ],
    "become": [
        "become",
        "becomes",
        "became",
        "becoming",
        "has become",
        "had become",
        "will become",
        "will have become",
    ],
    "leave": [
        "leave",
        "leaves",
        "left",
        "leaving",
        "has left",
        "had left",
        "will leave",
        "will have left",
    ],
    "put": [
        "put",
        "puts",
        "putting",
        "has put",
        "had put",
        "will put",
        "will have put",
    ],
    "mean": [
        "mean",
        "means",
        "meant",
        "meaning",
        "has meant",
        "had meant",
        "will mean",
        "will have meant",
    ],
    "keep": [
        "keep",
        "keeps",
        "kept",
        "keeping",
        "has kept",
        "had kept",
        "will keep",
        "will have kept",
    ],
    "let": [
        "let",
        "lets",
        "letting",
        "has let",
        "had let",
        "will let",
        "will have let",
    ],
    "begin": [
        "begin",
        "begins",
        "began",
        "beginning",
        "has begun",
        "had begun",
        "will begin",
        "will have begun",
    ],
    "seem": [
        "seem",
        "seems",
        "seemed",
        "seeming",
        "has seemed",
        "had seemed",
        "will seem",
        "will have seemed",
    ],
    "help": [
        "help",
        "helps",
        "helped",
        "helping",
        "has helped",
        "had helped",
        "will help",
        "will have helped",
    ],
    "talk": [
        "talk",
        "talks",
        "talked",
        "talking",
        "has talked",
        "had talked",
        "will talk",
        "will have talked",
    ],
    "turn": [
        "turn",
        "turns",
        "turned",
        "turning",
        "has turned",
        "had turned",
        "will turn",
        "will have turned",
    ],
    "start": [
        "start",
        "starts",
        "started",
        "starting",
        "has started",
        "had started",
        "will start",
        "will have started",
    ],
    "show": [
        "show",
        "shows",
        "showed",
        "showing",
        "has shown",
        "had shown",
        "will show",
        "will have shown",
    ],
    "hear": [
        "hear",
        "hears",
        "heard",
        "hearing",
        "has heard",
        "had heard",
        "will hear",
        "will have heard",
    ],
    "play": [
        "play",
        "plays",
        "played",
        "playing",
        "has played",
        "had played",
        "will play",
        "will have played",
    ],
    "run": [
        "run",
        "runs",
        "ran",
        "running",
        "has run",
        "had run",
        "will run",
        "will have run",
    ],
    "move": [
        "move",
        "moves",
        "moved",
        "moving",
        "has moved",
        "had moved",
        "will move",
        "will have moved",
    ],
    "like": [
        "like",
        "likes",
        "liked",
        "liking",
        "has liked",
        "had liked",
        "will like",
        "will have liked",
    ],
    "live": [
        "live",
        "lives",
        "lived",
        "living",
        "has lived",
        "had lived",
        "will live",
        "will have lived",
    ],
    "believe": [
        "believe",
        "believes",
        "believed",
        "believing",
        "has believed",
        "had believed",
        "will believe",
        "will have believed",
    ],
    "hold": [
        "hold",
        "holds",
        "held",
        "holding",
        "has held",
        "had held",
        "will hold",
        "will have held",
    ],
    "bring": [
        "bring",
        "brings",
        "brought",
        "bringing",
        "has brought",
        "had brought",
        "will bring",
        "will have brought",
    ],
    "happen": [
        "happen",
        "happens",
        "happened",
        "happening",
        "has happened",
        "had happened",
        "will happen",
        "will have happened",
    ],
    "must": [
        "must",
    ],
    "write": [
        "write",
        "writes",
        "wrote",
        "writing",
        "has written",
        "had written",
        "will write",
        "will have written",
    ],
    "provide": [
        "provide",
        "provides",
        "provided",
        "providing",
        "has provided",
        "had provided",
        "will provide",
        "will have provided",
    ],
    "sit": [
        "sit",
        "sits",
        "sat",
        "sitting",
        "has sat",
        "had sat",
        "will sit",
        "will have sat",
    ],
    "stand": [
        "stand",
        "stands",
        "stood",
        "standing",
        "has stood",
        "had stood",
        "will stand",
        "will have stood",
    ],
    "lose": [
        "lose",
        "loses",
        "lost",
        "losing",
        "has lost",
        "had lost",
        "will lose",
        "will have lost",
    ],
    "pay": [
        "pay",
        "pays",
        "paid",
        "paying",
        "has paid",
        "had paid",
        "will pay",
        "will have paid",
    ],
    "meet": [
        "meet",
        "meets",
        "met",
        "meeting",
        "has met",
        "had met",
        "will meet",
        "will have met",
    ],
    "include": [
        "include",
        "includes",
        "included",
        "including",
        "has included",
        "had included",
        "will include",
        "will have included",
    ],
    "continue": [
        "continue",
        "continues",
        "continued",
        "continuing",
        "has continued",
        "had continued",
        "will continue",
        "will have continued",
    ],
    "set": [
        "set",
        "sets",
        "setting",
        "has set",
        "had set",
        "will set",
        "will have set",
    ],
    "learn": [
        "learn",
        "learns",
        "learned",
        "learning",
        "has learned",
        "had learned",
        "will learn",
        "will have learned",
    ],
    "change": [
        "change",
        "changes",
        "changed",
        "changing",
        "has changed",
        "had changed",
        "will change",
        "will have changed",
    ],
    "lead": [
        "lead",
        "leads",
        "led",
        "leading",
        "has led",
        "had led",
        "will lead",
        "will have led",
    ],
    "understand": [
        "understand",
        "understands",
        "understood",
        "understanding",
        "has understood",
        "had understood",
        "will understand",
        "will have understood",
    ],
    "watch": [
        "watch",
        "watches",
        "watched",
        "watching",
        "has watched",
        "had watched",
        "will watch",
        "will have watched",
    ],
    "follow": [
        "follow",
        "follows",
        "followed",
        "following",
        "has followed",
        "had followed",
        "will follow",
        "will have followed",
    ],
    "stop": [
        "stop",
        "stops",
        "stopped",
        "stopping",
        "has stopped",
        "had stopped",
        "will stop",
        "will have stopped",
    ],
    "create": [
        "create",
        "creates",
        "created",
        "creating",
        "has created",
        "had created",
        "will create",
        "will have created",
    ],
    "speak": [
        "speak",
        "speaks",
        "spoke",
        "speaking",
        "has spoken",
        "had spoken",
        "will speak",
        "will have spoken",
    ],
    "read": [
        "read",
        "reads",
        "reading",
        "has read",
        "had read",
        "will read",
        "will have read",
    ],
    "add": [
        "add",
        "adds",
        "added",
        "adding",
        "has added",
        "had added",
        "will add",
        "will have added",
    ],
    "spend": [
        "spend",
        "spends",
        "spent",
        "spending",
        "has spent",
        "had spent",
        "will spend",
        "will have spent",
    ],
    "grow": [
        "grow",
        "grows",
        "grew",
        "grown",
        "growing",
        "has grown",
        "had grown",
        "will grow",
        "will have grown",
    ],
    "open": [
        "open",
        "opens",
        "opened",
        "opening",
        "has opened",
        "had opened",
        "will open",
        "will have opened",
    ],
    "walk": [
        "walk",
        "walks",
        "walked",
        "walking",
        "has walked",
        "had walked",
        "will walk",
        "will have walked",
    ],
    "win": [
        "win",
        "wins",
        "won",
        "winning",
        "has won",
        "had won",
        "will win",
        "will have won",
    ],
    "offer": [
        "offer",
        "offers",
        "offered",
        "offering",
        "has offered",
        "had offered",
        "will offer",
        "will have offered",
    ],
    "remember": [
        "remember",
        "remembers",
        "remembered",
        "remembering",
        "has remembered",
        "had remembered",
        "will remember",
        "will have remembered",
    ],
    "love": [
        "love",
        "loves",
        "loved",
        "loving",
        "has loved",
        "had loved",
        "will love",
        "will have loved",
    ],
    "consider": [
        "consider",
        "considers",
        "considered",
        "considering",
        "has considered",
        "had considered",
        "will consider",
        "will have considered",
    ],
    "appear": [
        "appear",
        "appears",
        "appeared",
        "appearing",
        "has appeared",
        "had appeared",
        "will appear",
        "will have appeared",
    ],
    "buy": [
        "buy",
        "buys",
        "bought",
        "buying",
        "has bought",
        "had bought",
        "will buy",
        "will have bought",
    ],
    "wait": [
        "wait",
        "waits",
        "waited",
        "waiting",
        "has waited",
        "had waited",
        "will wait",
        "will have waited",
    ],
    "serve": [
        "serve",
        "serves",
        "served",
        "serving",
        "has served",
        "had served",
        "will serve",
        "will have served",
    ],
    "die": [
        "die",
        "dies",
        "died",
        "dying",
        "has died",
        "had died",
        "will die",
        "will have died",
    ],
    "send": [
        "send",
        "sends",
        "sent",
        "sending",
        "has sent",
        "had sent",
        "will send",
        "will have sent",
    ],
    "expect": [
        "expect",
        "expects",
        "expected",
        "expecting",
        "has expected",
        "had expected",
        "will expect",
        "will have expected",
    ],
    "build": [
        "build",
        "builds",
        "built",
        "building",
        "has built",
        "had built",
        "will build",
        "will have built",
    ],
    "stay": [
        "stay",
        "stays",
        "stayed",
        "staying",
        "has stayed",
        "had stayed",
        "will stay",
        "will have stayed",
    ],
    "fall": [
        "fall",
        "falls",
        "fell",
        "fallen",
        "falling",
        "has fallen",
        "had fallen",
        "will fall",
        "will have fallen",
    ],
    "cut": [
        "cut",
        "cuts",
        "cutting",
        "has cut",
        "had cut",
        "will cut",
        "will have cut",
    ],
    "reach": [
        "reach",
        "reaches",
        "reached",
        "reaching",
        "has reached",
        "had reached",
        "will reach",
        "will have reached",
    ],
    "kill": [
        "kill",
        "kills",
        "killed",
        "killing",
        "has killed",
        "had killed",
        "will kill",
        "will have killed",
    ],
    "remain": [
        "remain",
        "remains",
        "remained",
        "remaining",
        "has remained",
        "had remained",
        "will remain",
        "will have remained",
    ],

    "support": [
        "support",
        "supports",
        "supported",
        "supporting",
        "has supported",
        "had supported",
        "will support",
        "will have supported",
    ],
    "hit": [
        "hit",
        "hits",
        "hitting",
        "has hit",
        "had hit",
        "will hit",
        "will have hit",
    ],
    "produce": [
        "produce",
        "produces",
        "produced",
        "producing",
        "has produced",
        "had produced",
        "will produce",
        "will have produced",
    ],
    "eat": [
        "eat",
        "eats",
        "ate",
        "eaten",
        "eating",
        "has eaten",
        "had eaten",
        "will eat",
        "will have eaten",
    ],
    "cover": [
        "cover",
        "covers",
        "covered",
        "covering",
        "has covered",
        "had covered",
        "will cover",
        "will have covered",
    ],
    "catch": [
        "catch",
        "catches",
        "caught",
        "catching",
        "has caught",
        "had caught",
        "will catch",
        "will have caught",
    ],
    "draw": [
        "draw",
        "draws",
        "drew",
        "drawn",
        "drawing",
        "has drawn",
        "had drawn",
        "will draw",
        "will have drawn",
    ],
    "choose": [
        "choose",
        "chooses",
        "chose",
        "chosen",
        "choosing",
        "has chosen",
        "had chosen",
        "will choose",
        "will have chosen",
    ],
    "form": [
        "form",
        "forms",
        "formed",
        "forming",
        "has formed",
        "had formed",
        "will form",
        "will have formed",
    ],
    "allow": [
        "allow",
        "allows",
        "allowed",
        "allowing",
        "has allowed",
        "had allowed",
        "will allow",
        "will have allowed",
    ],

    "suggest": [
        "suggest",
        "suggests",
        "suggested",
        "suggesting",
        "has suggested",
        "had suggested",
        "will suggest",
        "will have suggested",
    ],
    "raise": [
        "raise",
        "raises",
        "raised",
        "raising",
        "has raised",
        "had raised",
        "will raise",
        "will have raised",
    ],
    "pass": [
        "pass",
        "passes",
        "passed",
        "passing",
        "has passed",
        "had passed",
        "will pass",
        "will have passed",
    ],
    "sell": [
        "sell",
        "sells",
        "sold",
        "selling",
        "has sold",
        "had sold",
        "will sell",
        "will have sold",
    ],
    "require": [
        "require",
        "requires",
        "required",
        "requiring",
        "has required",
        "had required",
        "will require",
        "will have required",
    ],
    "report": [
        "report",
        "reports",
        "reported",
        "reporting",
        "has reported",
        "had reported",
        "will report",
        "will have reported",
    ],
    "decide": [
        "decide",
        "decides",
        "decided",
        "deciding",
        "has decided",
        "had decided",
        "will decide",
        "will have decided",
    ],
    "pull": [
        "pull",
        "pulls",
        "pulled",
        "pulling",
        "has pulled",
        "had pulled",
        "will pull",
        "will have pulled",
    ],

    "agree": [
        "agree",
        "agrees",
        "agreed",
        "agreeing",
        "has agreed",
        "had agreed",
        "will agree",
        "will have agreed",
    ],
    "explain": [
        "explain",
        "explains",
        "explained",
        "explaining",
        "has explained",
        "had explained",
        "will explain",
        "will have explained",
    ],
    "hope": [
        "hope",
        "hopes",
        "hoped",
        "hoping",
        "has hoped",
        "had hoped",
        "will hope",
        "will have hoped",
    ],
    "develop": [
        "develop",
        "develops",
        "developed",
        "developing",
        "has developed",
        "had developed",
        "will develop",
        "will have developed",
    ],
    "carry": [
        "carry",
        "carries",
        "carried",
        "carrying",
        "has carried",
        "had carried",
        "will carry",
        "will have carried",
    ],
    "break": [
        "break",
        "breaks",
        "broke",
        "broken",
        "breaking",
        "has broken",
        "had broken",
        "will break",
        "will have broken",
    ],
    "receive": [
        "receive",
        "receives",
        "received",
        "receiving",
        "has received",
        "had received",
        "will receive",
        "will have received",
    ],

    "accept": [
        "accept",
        "accepts",
        "accepted",
        "accepting",
        "has accepted",
        "had accepted",
        "will accept",
        "will have accepted",
    ],
    "admit": [
        "admit",
        "admits",
        "admitted",
        "admitting",
        "has admitted",
        "had admitted",
        "will admit",
        "will have admitted",
    ],
    "afford": [
        "afford",
        "affords",
        "afforded",
        "affording",
        "has afforded",
        "had afforded",
        "will afford",
        "will have afforded",
    ],
    "announce": [
        "announce",
        "announces",
        "announced",
        "announcing",
        "has announced",
        "had announced",
        "will announce",
        "will have announced",
    ],
    "answer": [
        "answer",
        "answers",
        "answered",
        "answering",
        "has answered",
        "had answered",
        "will answer",
        "will have answered",
    ],
    "apply": [
        "apply",
        "applies",
        "applied",
        "applying",
        "has applied",
        "had applied",
        "will apply",
        "will have applied",
    ],
    "arrive": [
        "arrive",
        "arrives",
        "arrived",
        "arriving",
        "has arrived",
        "had arrived",
        "will arrive",
        "will have arrived",
    ],
    "attach": [
        "attach",
        "attaches",
        "attached",
        "attaching",
        "has attached",
        "had attached",
        "will attach",
        "will have attached",
    ],
    "avoid": [
        "avoid",
        "avoids",
        "avoided",
        "avoiding",
        "has avoided",
        "had avoided",
        "will avoid",
        "will have avoided",
    ],
    "beat": [
        "beat",
        "beats",
        "beat",
        "beaten",
        "beating",
        "has beaten",
        "had beaten",
        "will beat",
        "will have beaten",
    ],
    "belong": [
        "belong",
        "belongs",
        "belonged",
        "belonging",
        "has belonged",
        "had belonged",
        "will belong",
        "will have belonged",
    ],
    "borrow": [
        "borrow",
        "borrows",
        "borrowed",
        "borrowing",
        "has borrowed",
        "had borrowed",
        "will borrow",
        "will have borrowed",
    ],
    "bother": [
        "bother",
        "bothers",
        "bothered",
        "bothering",
        "has bothered",
        "had bothered",
        "will bother",
        "will have bothered",
    ],
    "burn": [
        "burn",
        "burns",
        "burned",
        "burnt",
        "burning",
        "has burned",
        "had burned",
        "will burn",
        "will have burned",
    ],
    "celebrate": [
        "celebrate",
        "celebrates",
        "celebrated",
        "celebrating",
        "has celebrated",
        "had celebrated",
        "will celebrate",
        "will have celebrated",
    ],
    "choose": [
        "choose",
        "chooses",
        "chose",
        "chosen",
        "choosing",
        "has chosen",
        "had chosen",
        "will choose",
        "will have chosen",
    ],
    "climb": [
        "climb",
        "climbs",
        "climbed",
        "climbing",
        "has climbed",
        "had climbed",
        "will climb",
        "will have climbed",
    ],
    "collect": [
        "collect",
        "collects",
        "collected",
        "collecting",
        "has collected",
        "had collected",
        "will collect",
        "will have collected",
    ],
    "compare": [
        "compare",
        "compares",
        "compared",
        "comparing",
        "has compared",
        "had compared",
        "will compare",
        "will have compared",
    ],
    "complain": [
        "complain",
        "complains",
        "complained",
        "complaining",
        "has complained",
        "had complained",
        "will complain",
        "will have complained",
    ],
    "confirm": [
        "confirm",
        "confirms",
        "confirmed",
        "confirming",
        "has confirmed",
        "had confirmed",
        "will confirm",
        "will have confirmed",
    ],
    "connect": [
        "connect",
        "connects",
        "connected",
        "connecting",
        "has connected",
        "had connected",
        "will connect",
        "will have connected",
    ],
    "contain": [
        "contain",
        "contains",
        "contained",
        "containing",
        "has contained",
        "had contained",
        "will contain",
        "will have contained",
    ],
    "convince": [
        "convince",
        "convinces",
        "convinced",
        "convincing",
        "has convinced",
        "had convinced",
        "will convince",
        "will have convinced",
    ],
    "cook": [
        "cook",
        "cooks",
        "cooked",
        "cooking",
        "has cooked",
        "had cooked",
        "will cook",
        "will have cooked",
    ],
    "count": [
        "count",
        "counts",
        "counted",
        "counting",
        "has counted",
        "had counted",
        "will count",
        "will have counted",
    ],
    "cover": [
        "cover",
        "covers",
        "covered",
        "covering",
        "has covered",
        "had covered",
        "will cover",
        "will have covered",
    ],
    "cross": [
        "cross",
        "crosses",
        "crossed",
        "crossing",
        "has crossed",
        "had crossed",
        "will cross",
        "will have crossed",
    ],
    "cry": [
        "cry",
        "cries",
        "cried",
        "crying",
        "has cried",
        "had cried",
        "will cry",
        "will have cried",
    ],
    "damage": [
        "damage",
        "damages",
        "damaged",
        "damaging",
        "has damaged",
        "had damaged",
        "will damage",
        "will have damaged",
    ],
    "dance": [
        "dance",
        "dances",
        "danced",
        "dancing",
        "has danced",
        "had danced",
        "will dance",
        "will have danced",
    ],
    "deliver": [
        "deliver",
        "delivers",
        "delivered",
        "delivering",
        "has delivered",
        "had delivered",
        "will deliver",
        "will have delivered",
    ],
    "deny": [
        "deny",
        "denies",
        "denied",
        "denying",
        "has denied",
        "had denied",
        "will deny",
        "will have denied",
    ],
    "describe": [
        "describe",
        "describes",
        "described",
        "describing",
        "has described",
        "had described",
        "will describe",
        "will have described",
    ],
    "design": [
        "design",
        "designs",
        "designed",
        "designing",
        "has designed",
        "had designed",
        "will design",
        "will have designed",
    ],
    "destroy": [
        "destroy",
        "destroys",
        "destroyed",
        "destroying",
        "has destroyed",
        "had destroyed",
        "will destroy",
        "will have destroyed",
    ],
    "discover": [
        "discover",
        "discovers",
        "discovered",
        "discovering",
        "has discovered",
        "had discovered",
        "will discover",
        "will have discovered",
    ],
    "divide": [
        "divide",
        "divides",
        "divided",
        "dividing",
        "has divided",
        "had divided",
        "will divide",
        "will have divided",
    ],
    "drop": [
        "drop",
        "drops",
        "dropped",
        "dropping",
        "has dropped",
        "had dropped",
        "will drop",
        "will have dropped",
    ],
    "escape": [
        "escape",
        "escapes",
        "escaped",
        "escaping",
        "has escaped",
        "had escaped",
        "will escape",
        "will have escaped",
    ],
    "examine": [
        "examine",
        "examines",
        "examined",
        "examining",
        "has examined",
        "had examined",
        "will examine",
        "will have examined",
    ],
    "exist": [
        "exist",
        "exists",
        "existed",
        "existing",
        "has existed",
        "had existed",
        "will exist",
        "will have existed",
    ],
    "expand": [
        "expand",
        "expands",
        "expanded",
        "expanding",
        "has expanded",
        "had expanded",
        "will expand",
        "will have expanded",
    ],
    "face": [
        "face",
        "faces",
        "faced",
        "facing",
        "has faced",
        "had faced",
        "will face",
        "will have faced",
    ],
    "fail": [
        "fail",
        "fails",
        "failed",
        "failing",
        "has failed",
        "had failed",
        "will fail",
        "will have failed",
    ],
    "fix": [
        "fix",
        "fixes",
        "fixed",
        "fixing",
        "has fixed",
        "had fixed",
        "will fix",
        "will have fixed",
    ],
    "fly": [
        "fly",
        "flies",
        "flew",
        "flown",
        "flying",
        "has flown",
        "had flown",
        "will fly",
        "will have flown",
    ],
    "forget": [
        "forget",
        "forgets",
        "forgot",
        "forgotten",
        "forgetting",
        "has forgotten",
        "had forgotten",
        "will forget",
        "will have forgotten",
    ],
    "freeze": [
        "freeze",
        "freezes",
        "froze",
        "frozen",
        "freezing",
        "has frozen",
        "had frozen",
        "will freeze",
        "will have frozen",
    ],
    "gather": [
        "gather",
        "gathers",
        "gathered",
        "gathering",
        "has gathered",
        "had gathered",
        "will gather",
        "will have gathered",
    ],
    "grab": [
        "grab",
        "grabs",
        "grabbed",
        "grabbing",
        "has grabbed",
        "had grabbed",
        "will grab",
        "will have grabbed",
    ],
    "handle": [
        "handle",
        "handles",
        "handled",
        "handling",
        "has handled",
        "had handled",
        "will handle",
        "will have handled",
    ],
    "hang": [
        "hang",
        "hangs",
        "hung",
        "hanging",
        "has hung",
        "had hung",
        "will hang",
        "will have hung",
    ],
    "imagine": [
        "imagine",
        "imagines",
        "imagined",
        "imagining",
        "has imagined",
        "had imagined",
        "will imagine",
        "will have imagined",
    ],
    "improve": [
        "improve",
        "improves",
        "improved",
        "improving",
        "has improved",
        "had improved",
        "will improve",
        "will have improved",
    ],
    "increase": [
        "increase",
        "increases",
        "increased",
        "increasing",
        "has increased",
        "had increased",
        "will increase",
        "will have increased",
    ],
    "introduce": [
        "introduce",
        "introduces",
        "introduced",
        "introducing",
        "has introduced",
        "had introduced",
        "will introduce",
        "will have introduced",
    ],
    "invite": [
        "invite",
        "invites",
        "invited",
        "inviting",
        "has invited",
        "had invited",
        "will invite",
        "will have invited",
    ],
    "join": [
        "join",
        "joins",
        "joined",
        "joining",
        "has joined",
        "had joined",
        "will join",
        "will have joined",
    ],
    "jump": [
        "jump",
        "jumps",
        "jumped",
        "jumping",
        "has jumped",
        "had jumped",
        "will jump",
        "will have jumped",
    ],
    "lay": [
        "lay",
        "lays",
        "laid",
        "laying",
        "has laid",
        "had laid",
        "will lay",
        "will have laid",
    ],
    "lend": [
        "lend",
        "lends",
        "lent",
        "lending",
        "has lent",
        "had lent",
        "will lend",
        "will have lent",
    ],
    "lock": [
        "lock",
        "locks",
        "locked",
        "locking",
        "has locked",
        "had locked",
        "will lock",
        "will have locked",
    ],
    "mark": [
        "mark",
        "marks",
        "marked",
        "marking",
        "has marked",
        "had marked",
        "will mark",
        "will have marked",
    ],
    "miss": [
        "miss",
        "misses",
        "missed",
        "missing",
        "has missed",
        "had missed",
        "will miss",
        "will have missed",
    ],
    "mix": [
        "mix",
        "mixes",
        "mixed",
        "mixing",
        "has mixed",
        "had mixed",
        "will mix",
        "will have mixed",
    ],
    "notice": [
        "notice",
        "notices",
        "noticed",
        "noticing",
        "has noticed",
        "had noticed",
        "will notice",
        "will have noticed",
    ],
    "offer": [
        "offer",
        "offers",
        "offered",
        "offering",
        "has offered",
        "had offered",
        "will offer",
        "will have offered",
    ],
    "pack": [
        "pack",
        "packs",
        "packed",
        "packing",
        "has packed",
        "had packed",
        "will pack",
        "will have packed",
    ],
    "paint": [
        "paint",
        "paints",
        "painted",
        "painting",
        "has painted",
        "had painted",
        "will paint",
        "will have painted",
    ],
    "pass": [
        "pass",
        "passes",
        "passed",
        "passing",
        "has passed",
        "had passed",
        "will pass",
        "will have passed",
    ],
    "pick": [
        "pick",
        "picks",
        "picked",
        "picking",
        "has picked",
        "had picked",
        "will pick",
        "will have picked",
    ],
    "plan": [
        "plan",
        "plans",
        "planned",
        "planning",
        "has planned",
        "had planned",
        "will plan",
        "will have planned",
    ],
    "point": [
        "point",
        "points",
        "pointed",
        "pointing",
        "has pointed",
        "had pointed",
        "will point",
        "will have pointed",
    ],
    "prefer": [
        "prefer",
        "prefers",
        "preferred",
        "preferring",
        "has preferred",
        "had preferred",
        "will prefer",
        "will have preferred",
    ],
    "prepare": [
        "prepare",
        "prepares",
        "prepared",
        "preparing",
        "has prepared",
        "had prepared",
        "will prepare",
        "will have prepared",
    ],
    "press": [
        "press",
        "presses",
        "pressed",
        "pressing",
        "has pressed",
        "had pressed",
        "will press",
        "will have pressed",
    ],
    "promise": [
        "promise",
        "promises",
        "promised",
        "promising",
        "has promised",
        "had promised",
        "will promise",
        "will have promised",
    ],
    "protect": [
        "protect",
        "protects",
        "protected",
        "protecting",
        "has protected",
        "had protected",
        "will protect",
        "will have protected",
    ],
    "prove": [
        "prove",
        "proves",
        "proved",
        "proven",
        "proving",
        "has proven",
        "had proven",
        "will prove",
        "will have proven",
    ],
    "push": [
        "push",
        "pushes",
        "pushed",
        "pushing",
        "has pushed",
        "had pushed",
        "will push",
        "will have pushed",
    ],
    "raise": [
        "raise",
        "raises",
        "raised",
        "raising",
        "has raised",
        "had raised",
        "will raise",
        "will have raised",
    ],
    "reach": [
        "reach",
        "reaches",
        "reached",
        "reaching",
        "has reached",
        "had reached",
        "will reach",
        "will have reached",
    ],
    "recognize": [
        "recognize",
        "recognizes",
        "recognized",
        "recognizing",
        "has recognized",
        "had recognized",
        "will recognize",
        "will have recognized",
    ],
    "reduce": [
        "reduce",
        "reduces",
        "reduced",
        "reducing",
        "has reduced",
        "had reduced",
        "will reduce",
        "will have reduced",
    ],
    "reflect": [
        "reflect",
        "reflects",
        "reflected",
        "reflecting",
        "has reflected",
        "had reflected",
        "will reflect",
        "will have reflected",
    ],
    "refuse": [
        "refuse",
        "refuses",
        "refused",
        "refusing",
        "has refused",
        "had refused",
        "will refuse",
        "will have refused",
    ],
    "regret": [
        "regret",
        "regrets",
        "regretted",
        "regretting",
        "has regretted",
        "had regretted",
        "will regret",
        "will have regretted",
    ],
    "release": [
        "release",
        "releases",
        "released",
        "releasing",
        "has released",
        "had released",
        "will release",
        "will have released",
    ],
    "remove": [
        "remove",
        "removes",
        "removed",
        "removing",
        "has removed",
        "had removed",
        "will remove",
        "will have removed",
    ],
    "replace": [
        "replace",
        "replaces",
        "replaced",
        "replacing",
        "has replaced",
        "had replaced",
        "will replace",
        "will have replaced",
    ],
    "reply": [
        "reply",
        "replies",
        "replied",
        "replying",
        "has replied",
        "had replied",
        "will reply",
        "will have replied",
    ],
    "require": [
        "require",
        "requires",
        "required",
        "requiring",
        "has required",
        "had required",
        "will require",
        "will have required",
    ],
    "return": [
        "return",
        "returns",
        "returned",
        "returning",
        "has returned",
        "had returned",
        "will return",
        "will have returned",
    ],
    "ring": [
        "ring",
        "rings",
        "rang",
        "rung",
        "ringing",
        "has rung",
        "had rung",
        "will ring",
        "will have rung",
    ],
    "roll": [
        "roll",
        "rolls",
        "rolled",
        "rolling",
        "has rolled",
        "had rolled",
        "will roll",
        "will have rolled",
    ],
    "save": [
        "save",
        "saves",
        "saved",
        "saving",
        "has saved",
        "had saved",
        "will save",
        "will have saved",
    ],
    "scream": [
        "scream",
        "screams",
        "screamed",
        "screaming",
        "has screamed",
        "had screamed",
        "will scream",
        "will have screamed",
    ],
    "search": [
        "search",
        "searches",
        "searched",
        "searching",
        "has searched",
        "had searched",
        "will search",
        "will have searched",
    ],
    "select": [
        "select",
        "selects",
        "selected",
        "selecting",
        "has selected",
        "had selected",
        "will select",
        "will have selected",
    ],
    "send": [
        "send",
        "sends",
        "sent",
        "sending",
        "has sent",
        "had sent",
        "will send",
        "will have sent",
    ],
    "shake": [
        "shake",
        "shakes",
        "shook",
        "shaken",
        "shaking",
        "has shaken",
        "had shaken",
        "will shake",
        "will have shaken",
    ],
    "share": [
        "share",
        "shares",
        "shared",
        "sharing",
        "has shared",
        "had shared",
        "will share",
        "will have shared",
    ],
    "shout": [
        "shout",
        "shouts",
        "shouted",
        "shouting",
        "has shouted",
        "had shouted",
        "will shout",
        "will have shouted",
    ],
    "sing": [
        "sing",
        "sings",
        "sang",
        "sung",
        "singing",
        "has sung",
        "had sung",
        "will sing",
        "will have sung",
    ],
    "smile": [
        "smile",
        "smiles",
        "smiled",
        "smiling",
        "has smiled",
        "had smiled",
        "will smile",
        "will have smiled",
    ],
    "solve": [
        "solve",
        "solves",
        "solved",
        "solving",
        "has solved",
        "had solved",
        "will solve",
        "will have solved",
    ],
    "spread": [
        "spread",
        "spreads",
        "spread",
        "spreading",
        "has spread",
        "had spread",
        "will spread",
        "will have spread",
    ],
    "steal": [
        "steal",
        "steals",
        "stole",
        "stolen",
        "stealing",
        "has stolen",
        "had stolen",
        "will steal",
        "will have stolen",
    ],
    "stretch": [
        "stretch",
        "stretches",
        "stretched",
        "stretching",
        "has stretched",
        "had stretched",
        "will stretch",
        "will have stretched",
    ],
    "succeed": [
        "succeed",
        "succeeds",
        "succeeded",
        "succeeding",
        "has succeeded",
        "had succeeded",
        "will succeed",
        "will have succeeded",
    ],
    "suggest": [
        "suggest",
        "suggests",
        "suggested",
        "suggesting",
        "has suggested",
        "had suggested",
        "will suggest",
        "will have suggested",
    ],
    "survive": [
        "survive",
        "survives",
        "survived",
        "surviving",
        "has survived",
        "had survived",
        "will survive",
        "will have survived",
    ],
    "swim": [
        "swim",
        "swims",
        "swam",
        "swum",
        "swimming",
        "has swum",
        "had swum",
        "will swim",
        "will have swum",
    ],
    "tear": [
        "tear",
        "tears",
        "tore",
        "torn",
        "tearing",
        "has torn",
        "had torn",
        "will tear",
        "will have torn",
    ],
    "throw": [
        "throw",
        "throws",
        "threw",
        "thrown",
        "throwing",
        "has thrown",
        "had thrown",
        "will throw",
        "will have thrown",
    ],
    "touch": [
        "touch",
        "touches",
        "touched",
        "touching",
        "has touched",
        "had touched",
        "will touch",
        "will have touched",
    ],
    "train": [
        "train",
        "trains",
        "trained",
        "training",
        "has trained",
        "had trained",
        "will train",
        "will have trained",
    ],
    "travel": [
        "travel",
        "travels",
        "traveled",
        "travelling",
        "has traveled",
        "had traveled",
        "will travel",
        "will have traveled",
    ],
    "treat": [
        "treat",
        "treats",
        "treated",
        "treating",
        "has treated",
        "had treated",
        "will treat",
        "will have treated",
    ],
    "trust": [
        "trust",
        "trusts",
        "trusted",
        "trusting",
        "has trusted",
        "had trusted",
        "will trust",
        "will have trusted",
    ],
    "visit": [
        "visit",
        "visits",
        "visited",
        "visiting",
        "has visited",
        "had visited",
        "will visit",
        "will have visited",
    ],
    "warn": [
        "warn",
        "warns",
        "warned",
        "warning",
        "has warned",
        "had warned",
        "will warn",
        "will have warned",
    ],
    "waste": [
        "waste",
        "wastes",
        "wasted",
        "wasting",
        "has wasted",
        "had wasted",
        "will waste",
        "will have wasted",
    ],
    "wish": [
        "wish",
        "wishes",
        "wished",
        "wishing",
        "has wished",
        "had wished",
        "will wish",
        "will have wished",
    ],
    "wonder": [
        "wonder",
        "wonders",
        "wondered",
        "wondering",
        "has wondered",
        "had wondered",
        "will wonder",
        "will have wondered",
    ],
    "yell": [
        "yell",
        "yells",
        "yelled",
        "yelling",
        "has yelled",
        "had yelled",
        "will yell",
        "will have yelled",
    ],
    "zoom": [
        "zoom",
        "zooms",
        "zoomed",
        "zooming",
        "has zoomed",
        "had zoomed",
        "will zoom",
        "will have zoomed",
    ],




    # other ...



    "i": ["I", 'me', 'my', 'mine', 'myself'],
    "you": ["you", 'your', 'yours', 'yourself', 'yourselves'],
    "he": ["he", 'him', 'his', 'himself'],
    "she": ["she", 'her', 'herslef'],
    "it": ["it", "its", "it's", "itself"],
    "we": ["we", 'wee'],
    "us": ["us"],
    "our": ["our", 'ours', 'ourselves'],
    "they": ["they"],
    "them": ["them", 'themselves'],
    "their": ["their", 'theirs'],
    "who": ["who", 'whom'],
    "whose": ["whose"],
    "which": ["which", 'whichever', 'witch'],
    "that": ["that", "thats", "that's"],
    "this": ["this", 'these', 'those'],
    "those": ["those"],
    "anyone": ["anyone"],
    "someone": ["someone", 'noone'],
    "everyone": ["everyone"],
    "each": ["each"],
    "either": ["either"],
    "neither": ["neither"],
    "all": ["all"],
    "some": ["some"],
    "none": ["none"],
    "few": ["few"],
    "many": ["many"],
    "most": ["most"],
    "several": ["several"],
    "one": ["one"],
    "two": ["two"],
    "three": ["three"],
    "first": ["first"],
    "second": ["second"],
    "third": ["third"],

    # Adjectives
    "good": ["good", 'god'],
    "bad": ["bad"],
    "happy": ["happy"],
    "sad": ["sad"],
    "big": ["big"],
    "small": ["small"],
    "large": ["large"],
    "short": ["short"],
    "long": ["long"],
    "young": ["young"],
    "old": ["old"],
    "new": ["new"],
    "high": ["high"],
    "low": ["low"],
    "early": ["early"],
    "late": ["late"],
    "easy": ["easy"],
    "hard": ["hard"],
    "strong": ["strong"],
    "weak": ["weak"],
    "hot": ["hot"],
    "cold": ["cold"],
    "fast": ["fast"],
    "slow": ["slow"],
    "beau": ["beautiful"],
    "belle": ["beautiful"],
    "ugly": ["ugly"],
    "rich": ["rich"],
    "poor": ["poor"],
    "clean": ["clean"],
    "dirty": ["dirty"],
    "right": ["right"],
    "wrong": ["wrong"],
    "dark": ["dark"],
    "light": ["light"],
    "full": ["full"],
    "empty": ["empty"],

    # Adverbs
    "very": ["very"],
    "quite": ["quite"],
    "really": ["really"],
    "just": ["just"],
    "almost": ["almost"],
    "always": ["always"],
    "never": ["never"],
    "often": ["often"],
    "sometimes": ["sometimes"],
    "usually": ["usually"],
    "rarely": ["rarely"],
    "soon": ["soon"],
    "now": ["now"],
    "then": ["then"],
    "here": ["here"],
    "there": ["there"],
    "everywhere": ["everywhere"],
    "anywhere": ["anywhere"],
    "nowhere": ["nowhere"],

    # Conjunctions
    "and": ["and"],
    "but": ["but"],
    "or": ["or"],
    "so": ["so"],
    "yet": ["yet"],
    "for": ["for"],
    "nor": ["nor"],
    "although": ["although"],
    "because": ["because"],
    "since": ["since"],
    "unless": ["unless"],
    "while": ["while"],
    "whereas": ["whereas"],
    "if": ["if"],
    "though": ["though"],

    # Prepositions
    "in": ["in"],
    "on": ["on"],
    "at": ["at"],
    "by": ["by"],
    "with": ["with"],
    "about": ["about"],
    "against": ["against"],
    "between": ["between"],
    "into": ["into"],
    "through": ["through"],
    "during": ["during"],
    "before": ["before"],
    "after": ["after"],
    "above": ["above"],
    "below": ["below"],
    "to": ["to"],
    "from": ["from"],
    "up": ["up"],
    "down": ["down"],
    "over": ["over"],
    "under": ["under"],
    "around": ["around"],
    "near": ["near"],
    "far": ["far"],

    # Determiners
    "the": ["the"],
    "a": ["a"],
    "an": ["an"],
    "some": ["some"],
    "any": ["any"],
    "no": ["no"],
    "each": ["each"],
    "every": ["every"],
    "either": ["either"],
    "neither": ["neither"],
    "much": ["much"],
    "many": ["many"],
    "few": ["few"],
    "several": ["several"],
    "all": ["all"],
    "both": ["both"],
    "other": ["other"],
    "another": ["another"],
    "such": ["such"],
}


WORD_MAP = create_word_map(WORDS_WITH_FORMS)

def get_word_forms_from_chord(chord_keys):
    """
    Given chord keys, return list of word forms if found, else None.
    """
    filtered = set()
    for c in sorted(chord_keys):
        if len(filtered) < 3:
            filtered.add(c)
        else:
            break
    chord_key = frozenset(filtered)
    return WORD_MAP.get(chord_key, None)
